const data = {
  en: {
    logo: 'Scratch',
    logoAlt: 'A simple note taking app',
    signup: 'Signup',
    login: 'Login',
    logout: 'Logout',
    email: 'Email',
    signupEmailText: 'We never share emails.',
    pass: 'Password',
    confirmPass: 'Confirm Password',
    loginPassText: 'Is it really you?',
    signupPassText: 'God knows no one can have it except the server.',
    verify: 'Verify',
    userExists: `We know know. Perhaps you'd like to login...`,
    confCode: 'Confirmation Code',
    confCodeText: 'Please check your email for the code.',
    loginSuccess: 'Welcome to your Scratch...',
    alreadyLoggedIn: `You are aleady logged in...`,
    unconfirmedUserMsg: 'You have to complete your sign up...',
    tooMuchConfReq: 'Too much requests. Try again after 15 minutes.',
    netError: 'Check your network connection.',
    userNotFound: `We don't know you. Come signup...`,
    settings: 'Settings',
  },
  ar: {
    logo: 'صيد الخاطر',
    logoAlt: 'العلم صيدٌ والكتابة قيدُه',
    signup: 'اركب معنا',
    login: 'افتح سِجلَّك',
    logout: 'أغلِق سِجلَّك',
    email: 'بريدك',
    signupEmailText: 'عنوانك محفوظ',
    pass: 'أمارتُك',
    confirmPass: 'أكِّد أمارتَك',
    loginPassText: 'أأنت أنت؟',
    signupPassText: 'لا يطّلع عليها إلا ربُّ العالمين والخادوم الأمين.',
    verify: 'تحقَّق',
    userExists: `إنا نعرفك، لعلك تريد أن تفتح سِجلَّك...`,
    confCode: 'رمز التحقق',
    confCodeText: 'انظر بريدك وأْتِ بالرمز.',
    loginSuccess: 'حياك الله في سِجلِّك...',
    alreadyLoggedIn: `سِجلّك مفتوح، اطّلع عليه...`,
    unconfirmedUserMsg: 'لا بد أن تُتمَّ التسجيل...',
    tooMuchConfReq: 'أكثرتَ الطلب. اصبر ربع ساعة ثم أعِد الكرّة.',
    netError: 'راجع اتصالك بالشبكة.',
    userNotFound: `لا نعرفك، تعالَ واركب معنا...`,
    settings: 'الضبط',
  },
};

export default data;
